# Generated by Django 4.2.3 on 2024-12-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summarize',
            field=models.TextField(null=True),
        ),
    ]
